import { parseStrategySource } from "./parser";
import type { ExportOptions } from "./types";

const DEFAULT_TEMPLATE = `//+------------------------------------------------------------------+
//| {{NAME}} — exported from Trading Santai Strategy Lab             |
//| {{LICENSE}}                                                      |
//+------------------------------------------------------------------+
#property copyright "Trading Santai"
#property version   "1.00"
#property strict

{{INPUTS}}

//--- indicator handles
int hRsi = INVALID_HANDLE;
int hMa  = INVALID_HANDLE;

//+------------------------------------------------------------------+
int OnInit()
{
{{INIT_HANDLES}}
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   if (hRsi != INVALID_HANDLE) IndicatorRelease(hRsi);
   if (hMa  != INVALID_HANDLE) IndicatorRelease(hMa);
}

double GetRsi(int period)
{
   double buf[];
   ArraySetAsSeries(buf, true);
   if (CopyBuffer(hRsi, 0, 0, 1, buf) < 1) return 50;
   return buf[0];
}

double GetMa(int period)
{
   double buf[];
   ArraySetAsSeries(buf, true);
   if (CopyBuffer(hMa, 0, 0, 1, buf) < 1) return iClose(_Symbol, PERIOD_CURRENT, 0);
   return buf[0];
}

double GetAtr(int period)
{
   int h = iATR(_Symbol, PERIOD_CURRENT, period);
   double buf[];
   ArraySetAsSeries(buf, true);
   if (CopyBuffer(h, 0, 0, 1, buf) < 1) { IndicatorRelease(h); return 0; }
   IndicatorRelease(h);
   return buf[0];
}

bool HasOpenPosition()
{
   for (int i = PositionsTotal() - 1; i >= 0; i--)
      if (PositionSelectByTicket(PositionGetTicket(i)))
         if (PositionGetString(POSITION_SYMBOL) == _Symbol) return true;
   return false;
}

void DoBuy(double slDist, double tpDist)
{
   if (HasOpenPosition()) return;
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl = ask - slDist;
   double tp = ask + tpDist;
   MqlTradeRequest req = {};
   MqlTradeResult  res = {};
   req.action   = TRADE_ACTION_DEAL;
   req.symbol   = _Symbol;
   req.volume   = 0.01;
   req.type     = ORDER_TYPE_BUY;
   req.price    = ask;
   req.sl       = sl;
   req.tp       = tp;
   req.deviation = 20;
   OrderSend(req, res);
}

void DoSell(double slDist, double tpDist)
{
   if (HasOpenPosition()) return;
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = bid + slDist;
   double tp = bid - tpDist;
   MqlTradeRequest req = {};
   MqlTradeResult  res = {};
   req.action   = TRADE_ACTION_DEAL;
   req.symbol   = _Symbol;
   req.volume   = 0.01;
   req.type     = ORDER_TYPE_SELL;
   req.price    = bid;
   req.sl       = sl;
   req.tp       = tp;
   req.deviation = 20;
   OrderSend(req, res);
}

//+------------------------------------------------------------------+
void OnTick()
{
{{ONTICK_BODY}}
}
//+------------------------------------------------------------------+
`;

function mapBodyToMql5(body: string): string {
  return body
    .replace(/\biRSI\s*\(\s*(\w+)\s*\)/g, "GetRsi($1)")
    .replace(/\biMA\s*\(\s*(\w+)\s*\)/g, "GetMa($1)")
    .replace(/\biEMA\s*\(\s*(\w+)\s*\)/g, "GetMa($1)")
    .replace(/\biATR\s*\(\s*(\w+)\s*\)/g, "GetAtr($1)")
    .replace(/\bSignalBuy\s*\(/g, "DoBuy(")
    .replace(/\bSignalSell\s*\(/g, "DoSell(")
    .replace(/\bClose\b/g, "iClose(_Symbol, PERIOD_CURRENT, 0)")
    .replace(/\bOpen\b/g, "iOpen(_Symbol, PERIOD_CURRENT, 0)")
    .replace(/\bHigh\b/g, "iHigh(_Symbol, PERIOD_CURRENT, 0)")
    .replace(/\bLow\b/g, "iLow(_Symbol, PERIOD_CURRENT, 0)")
    .replace(/\bdouble\b/g, "")
    .replace(/\bint\b(?!\s+\w+\s*=)/g, "");
}

export function exportToMql5(
  source: string,
  options: ExportOptions,
): { ok: boolean; content?: string; error?: string } {
  const parsed = parseStrategySource(source);
  if (!parsed.ok) {
    return { ok: false, error: parsed.errors.join(" ") };
  }

  const inputsBlock = parsed.inputs
    .map((i) => `input ${i.type === "int" ? "int" : "double"} ${i.name} = ${i.value};`)
    .join("\n");

  const rsiPeriod = parsed.inputs.find((i) => i.name.toLowerCase().includes("rsi"))?.value ?? 14;
  const maPeriod = parsed.inputs.find((i) => i.name.toLowerCase().includes("ma"))?.value ?? 21;

  const initHandles = `   hRsi = iRSI(_Symbol, PERIOD_CURRENT, ${rsiPeriod}, PRICE_CLOSE);
   hMa  = iMA(_Symbol, PERIOD_CURRENT, ${maPeriod}, 0, MODE_EMA, PRICE_CLOSE);`;

  const mqlBody = mapBodyToMql5(parsed.onTickBody)
    .split("\n")
    .map((l) => "   " + l.trim())
    .filter((l) => l.trim())
    .join("\n");

  const license = options.licensedTo
    ? `Licensed to: ${options.licensedTo}`
    : "Generated by Trading Santai Strategy Lab";

  const content = DEFAULT_TEMPLATE
    .replace("{{NAME}}", options.strategyName)
    .replace("{{LICENSE}}", license)
    .replace("{{INPUTS}}", inputsBlock)
    .replace("{{INIT_HANDLES}}", initHandles)
    .replace("{{ONTICK_BODY}}", mqlBody);

  return { ok: true, content };
}

export function downloadMql5File(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".mq5") ? filename : `${filename}.mq5`;
  a.click();
  URL.revokeObjectURL(url);
}

/** Unduh file referensi EA dari public/strategy-lab */
export async function downloadReferenceMq5(
  url: string,
  filename: string,
): Promise<void> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Gagal mengunduh referensi: ${res.status}`);
  const content = await res.text();
  downloadMql5File(content, filename);
}